tiem:
  token:
    # 是否启用，默认true
    enabled: true
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # token存储方式：HEADER,COOKIE,ALL，默认ALL
    token-storage: 
      - HEADER
      - COOKIE
    # token前缀，默认Bearer，可以设置为空
    token-prefix: "Bearer "
    # cookie过期时间，单位秒，默认-1（浏览器关闭时过期）
    cookie-max-age: -1
    # cookie路径，默认/
    cookie-path: /
    # cookie域名，默认空
    cookie-domain: 
    # 是否启用httpOnly，默认true
    cookie-http-only: true
    # token存储类型：memory或redis，默认memory
    store-type: memory
    # token过期时间，单位秒，默认30分钟
    token-expire-time: 1800
    # token有效期（必定过期）单位: 秒，默认一天
    timeout: 86400
    # token临时有效期（指定时间无操作就过期）单位: 秒，默认30分钟
    active-timeout: 1800
    # 是否允许同一账号并发登录
    concurrent: true
    # 是否共用token
    share: true
    # 是否输出操作日志
    log: true

spring:
  main:
    allow-bean-definition-overriding: true 